name: folly_fields_example
description: A new Flutter project.

publish_to: 'none'

version: 0.10.17+142

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: 2.3.6

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_highlight
  flutter_highlight: 0.7.0

  # https://github.com/edufolly/folly_fields
  folly_fields:
    path: ../

  # https://pub.dev/packages/google_fonts
  google_fonts: 3.0.1

  # https://pub.dev/packages/http
  http: 0.13.4

  # https://pub.dev/packages/url_launcher
  url_launcher: 6.1.5

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
