name: folly_fields
description: Basic form fields and utilities.
version: 0.11.0+143
# author:
homepage: https://edufolly.github.io/folly_fields/

publish_to: 'none' # TODO - Remove to publish

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^2.0.0

  # https://pub.dev/packages/cpf_cnpj_validator
  cpf_cnpj_validator: ^2.0.0

  # https://pub.dev/packages/dial_picker
  dial_picker: ^1.0.1

  # https://pub.dev/packages/email_validator
  email_validator: ^2.0.1

  # https://pub.dev/packages/expandable
  expandable: ^5.0.1

  # https://pub.dev/packages/file_picker
  file_picker: ^4.6.1
    
  # https://flutter.dev/
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_colorpicker
  flutter_colorpicker: ^1.0.2

  # https://flutter.dev/
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 10.2.1

  # https://pub.dev/packages/sprintf
  sprintf: ^6.0.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

  # https://flutter.dev/
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
