name: folly_fields
description: Basic form fields and utilities.
version: 2.1.0
repository: https://github.com/edufolly/folly_fields/
homepage: https://edufolly.github.io/folly_fields/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^4.0.0

  # https://pub.dev/packages/cpf_cnpj_validator
  cpf_cnpj_validator: ^2.0.0

  # https://pub.dev/packages/dial_picker
  dial_picker: ^1.0.1

  # https://pub.dev/packages/email_validator
  email_validator: ^2.1.17

  # https://pub.dev/packages/expandable
  expandable: ^5.0.1

  # https://pub.dev/packages/file_picker
  file_picker: ^5.3.0

  # https://flutter.dev/
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_colorpicker
  flutter_colorpicker: ^1.0.3

  # https://flutter.dev/
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.5.0

  # https://pub.dev/packages/intl
  intl: ^0.18.0

  # https://pub.dev/packages/sprintf
  sprintf: ^7.0.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

  # https://flutter.dev/
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ^1.1.0

flutter:
  uses-material-design: true
