name: folly_fields
description: Basic form fields and utilities.
version: 0.6.3+101
# author:
homepage: https://edufolly.github.io/folly_fields/

publish_to: 'none' # TODO - Remove to publish

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.0

dependencies:
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^2.0.0

  # https://pub.dev/packages/cpf_cnpj_validator
  cpf_cnpj_validator: ^2.0.0

  # https://pub.dev/packages/email_validator
  email_validator: ^2.0.1

  # https://pub.dev/packages/expandable
  expandable: ^5.0.1

  # https://flutter.dev/
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_colorpicker
  # flutter_colorpicker: ^0.6.0
  flutter_colorpicker: ^1.0.2

  # https://flutter.dev/
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 9.2.0

  # https://pub.dev/packages/sprintf
  sprintf: ^6.0.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^1.0.0

  # https://flutter.dev/
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
