name: folly_fields
description: Basic form fields and utilities.
version: 4.4.0
repository: https://github.com/edufolly/folly_fields/
homepage: https://edufolly.github.io/folly_fields/

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  # https://pub.dev/packages/cpf_cnpj_validator
  cpf_cnpj_validator: ^2.0.0

  # https://pub.dev/packages/email_validator
  email_validator: ^3.0.0

  # https://pub.dev/packages/expandable
  expandable: ^5.0.1

  # https://flutter.dev/
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_colorpicker
  flutter_colorpicker: ^1.1.0

  # https://flutter.dev/
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.12.0

  # https://pub.dev/packages/intl
  intl: ^0.20.0

  # https://pub.dev/packages/sprintf
  sprintf: ^7.0.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0

  # https://flutter.dev/
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ^1.6.0

  # https://pub.dev/packages/yaml
  yaml: ^3.1.3

flutter:
  uses-material-design: true
