name: Dart Code Metrics

on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  check:
    name: dart-code-metrics-action
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Dart Code Metrics
        uses: dart-code-checker/dart-code-metrics-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fatal_warnings: true
          fatal_performance: true
          fatal_style: true
          check_unused_files: false
          pull_request_comment: true
